language: php

php:
  - 5.6

sudo: false

before_script:
  - travis -f setup
  - cp .env.travis .env
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed
  
script:
  - vendor/bin/phpmd app text codesize design naming unusedcode
  - vendor/bin/phpunit --testdox --coverage-text tests

notifications:
  email:
    recipients:
      - rachellesalvadora@gmail.com
      on_success: always
      on_failure: always